logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:4000/uaa/users/current
      #below configuration for test only purpose. ResourceServerProperties include clientId, clientSecret which were provided from security:  oauth2:    client:
      # and userInfoUri tokenInfoUri were provided from here, but if open this configuration. will get exception says two token service.
      #token-info-uri: http://localhost:4000/uaa/oauth/token
spring:
  rabbitmq:
    host: localhost