hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
#  ignoredServices: '*'

  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    # http://localhost:2244/compute/add?a=1&b=22    direct access

#   http://localhost:4000/compute-service/compute/add?a=1&b=26   access by Eureka exposed service, need to comment out ignoredServices


  # http://localhost:4000/compute/add?a=1&b=66    route by routers, can be mapped by service id or url
#    compute-service:
#        path: /compute/**
#        url: http://localhost:2244
#        stripPrefix: false
#        sensitiveHeaders:

    tt-service:
        path: /compute/**
        serviceId: compute-service
        stripPrefix: false
        sensitiveHeaders:

  # remember to add context path to each server, a also need to add /computer to the request url

#http://localhost:4000/feign-consumer/add?a=1&b=26    access by feign, remember to add context path feign-consumer/

    feign-consumer:
        path: /feign-consumer/**
        serviceId: feign-consumer
        stripPrefix: false
        sensitiveHeaders:

# http://localhost:4000/ribbon-consumer/add?a=1&b=009   access by ribbon
    ribbon-consumer:
        path: /ribbon-consumer/**
        serviceId: ribbon-consumer
        stripPrefix: false
        sensitiveHeaders:


    auth-service:
        path: /uaa/**
        serviceId: auth-service
        stripPrefix: false
        sensitiveHeaders:

    account-service:
        path: /accounts/**
        serviceId: account-service
        stripPrefix: false
        sensitiveHeaders:

    statistics-service:
        path: /statistics/**
        serviceId: statistics-service
        stripPrefix: false
        sensitiveHeaders:

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
