security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: STATISTICS_SERVICE_PASSWORD
      accessTokenUri: http://localhost:4000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      username: kevin1
      password: abc123
      database: test
      port: 27017


server:
  context-path: /statistics
  port: 7000

rates:
  url: http://api.fixer.io